ECOMMERCE/ecommerceproject/cart/urls.py
from django.urls import path
from . import views
app_name='cart'


urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ECOMMERCE/ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('', include('shopapp.urls')),
    path('/search/', include('searchapp.urls')),
    path('/cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ECOMMERCE/ecommerceproject/searchapp/urls.py
from django.urls import path
from . import views

app_name = 'searchapp'

urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
    ]

ECOMMERCE/ecommerceproject/shopapp/urls.py
from django.urls import path
from . import views

app_name = 'shopapp'

urlpatterns = [
    path('',views.allProdCat,name='allproducts'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/',views.prodDetails,name='prodcatdetails')
]

ECOMMERCE/ecommerceproject/cart/models.py
from django.db import models

from shopapp.models import Product


# Create your models here.
class Cart(models.Model):
        objects = None
        cart_id = models.CharField(max_length=250,blank=True)
        date_added = models.DateField(auto_now_add=True)

        class Meta:
                db_table='Cart'
                ordering=['date_added']

        def __str__(self):
                return '{}'.format(self.cart_id)


class CartItem(models.Model):
        product = models.ForeignKey(Product,on_delete=models.CASCADE)
        cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
        quantity = models.IntegerField()
        active = models.BooleanField(default=True)

        class Meta:
                db_table = 'CartItem'

        def sub_total(self):
                return self.product.price * self.quantity

        def __str__(self):
                return '{}'.format(self.product)

ECOMMERCE/ecommerceproject/searchapp/models.py
from django.db import models

# Create your models here.

ECOMMERCE/ecommerceproject/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
            name = models.CharField(max_length=250,unique=True)
            slug = models.SlugField(max_length=250,unique=True)
            desc = models.TextField(blank=True)
            img = models.ImageField(upload_to='category',blank=True)

            class Meta:
                    ordering = ('name',)
                    verbose_name = 'category'
                    verbose_name_plural = 'categories'

            def get_url(self):
                    return reverse('shopapp:products_by_category',args=[self.slug])

            def __str__(self):
                 return '{}'.format(self.name)


class Product(models.Model):
            objects = None
            name = models.CharField(max_length=250,unique=True)
            slug = models.SlugField(max_length=250,unique=True)
            desc = models.TextField(blank=True)
            img = models.ImageField(upload_to='product',blank=True)
            price = models.DecimalField(max_digits=10,decimal_places=2)
            category = models.ForeignKey(Category,on_delete=models.CASCADE)
            stock = models.IntegerField()
            available = models.BooleanField(default=True)
            created_date = models.DateTimeField(auto_now_add=True)
            updated_date = models.DateTimeField(auto_now=True)

            class Meta:
                    ordering = ('name',)
                    verbose_name = 'product'
                    verbose_name_plural = 'products'

            def get_url(self):
                    return reverse('shopapp:prodcatdetails',args=[self.category.slug,self.slug])

            def __str__(self):
                 return '{}'.format(self.name)

ECOMMERCE/ecommerceproject/cart/views.py
from collections import Counter
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from shopapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ECOMMERCE/ecommerceproject/searchapp/views.py
from django.db.models import Q
from django.shortcuts import render
from shopapp.models import Product

# Create your views here.
def SearchResult(request):
    query = None
    products = None

    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.filter(Q(name__icontains=query))

    return render(request, 'search.html', {'query': query, 'products': products})

ECOMMERCE/ecommerceproject/shopapp/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.shortcuts import render, get_object_or_404

from shopapp.models import Category, Product


# Create your views here.
def allProdCat(request, c_slug=None):
    c_page = None
    product_list = None

    # if slug is passed,display the page c_page using the slug(using slug we can find the category) or show 404 page.Then filter the products based on the category and which is available
    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        product_list = Product.objects.all().filter(category=c_page, available=True)



    # else show all the products irrespective of category
    else:
        product_list = Product.objects.all().filter(available=True)
    paginator = Paginator(product_list, 1)

    try:
        page = int(request.GET.get('page', '1'))

    except:
        page = 1

    try:
        product = paginator.page(page)

    except (EmptyPage, InvalidPage):
        product = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': c_page, 'product': product})


def prodDetails(request, c_slug, p_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)

    except Exception as e:
        raise e

    return render(request, 'product.html', {'product': product})

ECOMMERCE/ecommerceproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/22768845f9.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}

    <div class="one">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </div>
</body>
</html>

ECOMMERCE/ecommerceproject/templates/ca1.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}

            Cart Page

{% endblock %}

{% block title %}
    Cart
{% endblock %}

{% block content %}


{% if not cart_items %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">Your Shopping Cart is empty</h1>
    <br>

    <p class="text-center">Please Click<a href="{% url 'shopapp:allproducts' %}"> Here</a> to continue shopping </p>
  </div>
</div>

{% else %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">Your Shopping Cart</h1>
    <br>
  </div>
  <div class="row mx-auto">
    <div class="col-10 col-sm-10col-md-10 col-lg-3 text-center">
      <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
          <th colspan="2">
            Your Items
          </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
          <td>
            <a href="cart_item.product.get_absolute_url"><img src="#" alt="" style="width:80px;height:80px;" class="float-left rounded custom_image"></a>

          </td>
          <td class="text-lef">
            {{cart_item.product.name}}
            <br>
            SKU: {{cart_item.product.id}}
            <br>
            Price: Rs{{cart_item.product.price}}
            <br>
            Quantity: {{cart_item.quantity}} x Rs {{cart_item}}

          </td>
           <div class="mx-auto">
            {% if product.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in product.paginator.page_range %}
                        <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if product.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
          <td>
            Rs {{cart_item.sub_total}}
          </td>
          {% if cart_item.quantity < cart_item.product.stock %}
          <td>
            <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-plus custom_icon"></i>></a>
            &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
            &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash"></i></a>


          </td>
          {% else %}
          <td>

            &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
            &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash"></i></a>

          </td>
        </tr>
        {% endif %}
        </tbody>

      </table>


    </div>


  </div>

</div>
{% endfor %}
{% endif %}
<div class="col-20 col-sm-20 col-md-20 col-lg-10 text-center btn btn-secondary btn-block my_custom_button" >checkout
</div>
<br>
<tbody>
        <tr>
          <td>
            Please review your shopping cart items before proceeding with payment
          </td>
        </tr>

        <tr>
          <td class="text-left">
            Your Total is: <strong>{{total}}</strong>
          </td>
        </tr>
        </tbody>
<div class="mx-auto">

        <a href="{% url 'shopapp:allproducts' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
      </div>
{% endblock %}

ECOMMERCE/ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
                     Cart Page

{% endblock %}
{% block title %}
   Cart 5min food delivery app

{% endblock %}
{% block content %}
{% if not cart_items %}
<div>

    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart is empty
        </h1>
        <br>
        <p class="text-center">
        please click <a href="{% url 'shopapp:allproducts' %}">Here</a>to continue shopping.



    </p>
</div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>
    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="table my_custom_thead">
                <tr>

                    <th colspan="5">
                        Your items
                    </th>

                </tr>

            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>


                <td class="text-lef">
                    <a href="#"><img src="{{cart_item.product.img.url}}" alt="" style="width:300px;height:300px;"class="float-left rounded custom_image"></a>
                    <br>
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    Price: $ {{cart_item.product.price}}
                    <br>
                    Qty : {{cart_item.quantity}} x $ {{cart_item}}

                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                 <a href="{% url 'cart:add_cart' cart_item.product.id %}"class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>
                 <a href="{% url 'cart:cart_remove' cart_item.product.id %}"class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                 <a href="{% url 'cart:full_remove' cart_item.product.id %}"class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                    <td>
                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}"class="custom_a"><i class="fa-solid fa-minus custom_icon"></i></a>
                        <a href="{% url 'cart:full_remove' cart_item.product.id %}"class="custom_icon"><i class="fa-solid fa-trash custom_icon"></i></a>
                    </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
            <tr>
              <th>
                Checkout
              </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                 Please review your shopping cart items before procedding with the order payment.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total is:<strong> {{ total }}</strong>

                </td>
            </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'shopapp:allproducts' %}" class="btn-secondary btn-block my_custom_button">Continue Shopping</a>
</div>
{% endif %}
</div>
</div>
</div>

{% endblock %}

ECOMMERCE/ecommerceproject/templates/category.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.desc | truncatewords:155 }}
    {% else %}
        Welcome to FOODY  5MIN food delivery services
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.title }} - FOODY
    {% else %}
        Here you can buy several FOOD ITEMS
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        {% if category %}
            <div class="row my-4">
                <div class="mx-auto">
                    <p><a href="{% url 'shopapp:allproducts' %}">all food items</a></p>
                </div>
            </div>
        {% endif %}

        <div class="mx-auto">
            {% if category %}
                <img class="my_image" src="{{ category.img.url }}" alt="{{ category.name }}" width="300" height="200">
            {% else %}
                <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" width="1250px">
            {% endif %}
        </div>

        {% if category %}
            <div>
                <h2 class="text-center my_title">{{ category.name }}</h2>
                <p class="text-justify">{{ category.desc }}</p>
            </div>
        {% else %}
            <div>
                <h1 class="text-center my_title">our food recipes</h1>
                <p class="text-justify">
                    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical
                    Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at
                    Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a
                    Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the
                    undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et
                    Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the
                    theory of ethics, very popular during the Renaissance.
                </p>
            </div>
        {% endif %}

        <div class="row mx-auto mt-4">
            {% for prod in product.object_list %}
                <div class="col-9 col-sm-12 col-md-4 col-lg-4 my-3">
                    <div class="card text-center" style="min-width: 18rem;">
                        <a href="{{ prod.get_url }}"><img class="card-img-top my_image" src="{{ prod.img.url }}" alt="{{ prod.name }}"></a>
                    </div>
                    <div class="card-body">
                        <h4>{{ prod.name }}</h4><br>
                        <p>{{ prod.price }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="mx-auto">
            {% if product.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in product.paginator.page_range %}
                        <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if product.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

ECOMMERCE/ecommerceproject/templates/footer.html
<div  class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; FOODY PVT Ltd.5min Food Delivery</p>
</div>

ECOMMERCE/ecommerceproject/templates/header.html
{% load static %}
<header>
    <H1 style="font-size:50px background-color:red "> FOODY</H1>
    <center>
        <a href="{% url 'shopapp:allproducts' %}"> <img src="{% static 'img/logo.png' %}" width="100" height="100"></a>
    </center>
    <h2>5 MIN FOOD DELIVERY APP</h2>
</header>

ECOMMERCE/ecommerceproject/templates/nav.html
<!DOCTYPE html>
<html>
<head>
  <!-- Include necessary CSS and Bootstrap stylesheets -->
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shopapp:allproducts' %}">Home</a>
          </li>

          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                       {% for cat in links %}
            <li class="nav-item"><a class="nav-link" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>

          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}">Your Cart({{item_count}})</a>
          </li>
          {% endif %}
        </ul>

        <form class="d-flex ms-auto" action="{% url 'searchapp:SearchResult' %}" role="search">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i>Search</button>
        </form>
      </div>
    </div>
  </nav>


  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

ECOMMERCE/ecommerceproject/templates/product.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
       {% if product %}
                {{ product.desc | truncatewords:155 }}
        {% else %}
            Welcome to FOODY food delivery services
        {% endif %}
{% endblock %}

{% block title %}
    {% if product %}
          {{product.title}} - FOODY

    {% else %}
        Here you can buy several foods items


    {% endif %}

{% endblock %}


{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
            <p><a href="{% url 'shopapp:allproducts' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> |  {{product.name}}</p>
    </div>
<div class="container">
<br>


    <div class="row">
        <div class="col-12 col-sm-12-col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.img.url}}" alt="{{product.name}}">
        </div>
    </div>
    <div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <h4 class="my_prod_title">{{product.name}}</h4>
            <h6>Rs.{{product.price}}</h6>
            <p  class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.desc}}</p>
            <br>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text">Out of Stock</p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}"><i class="fa-solid fa-cart-shopping"></i>Add to Cart</a>
            {% endif %}
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}

ECOMMERCE/ecommerceproject/templates/search.html
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}

            Search Product List

{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: <b>"{{query}}"</b></p>
</div>

<div class="container">
    <div class="row mx_auto">
        {% for prod in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
        <div class="card text-center" style="min-width:18rem;">
            <a href="{{prod.get_url}}"><img class="card-img-top my_image" src="{{prod.img.url}}" alt="{{prod.name}}"></a>
        </div>

        <div class="card-body">
            <h4>{{prod.name}}</h4><br>
            <p>{{prod.price}}</p>
        </div>
        </div>
    </div>
</div>
    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">0 results found</p>
    </div>
    {% endfor %}
{% endblock %}